[build]
skip = ["pp*"]  # PyPyはビルドしない

[build.macos]
archs = ["x86_64", "arm64"]  # Apple SiliconとIntel Mac両対応
environment = { CMAKE_OSX_ARCHITECTURES = "x86_64;arm64" }
before-all = "brew install python@3.8 python@3.9 python@3.10 python@3.11 python@3.12 python@3.13"
